return {
  {
    "clangd",
    mason_id = true,
    require_node = false,
    hook_lspconfig = false,
    auto_install = true,
  },
  {
    "html",
    mason_id = "html-lsp",
    require_node = true,
    hook_lspconfig = true,
    auto_install = true,
  },
  {
    "cssls",
    mason_id = "css-lsp",
    require_node = true,
    hook_lspconfig = true,
    auto_install = true,
  },
  {
    "lua_ls",
    mason_id = "lua-language-server",
    require_node = false,
    hook_lspconfig = true,
    auto_install = true,
  },
  {
    "pyright",
    mason_id = true,
    require_node = true,
    hook_lspconfig = true,
    auto_install = true,
  },
  {
    "rust_analyzer",
    mason_id = "rust-analyzer",
    require_node = false,
    hook_lspconfig = true,
    auto_install = true,
  },
  {
    "tsserver",
    mason_id = "typescript-language-server",
    require_node = true,
    hook_lspconfig = false,
    auto_install = true,
  },
  {
    "blue",
    mason_id = true,
    require_node = false,
    auto_install = true,
  },
  {
    "jsonlint",
    mason_id = true,
    require_node = true,
    auto_install = true,
  },
  {
    "prettierd",
    mason_id = true,
    require_node = true,
    auto_install = true,
  },
  {
    "shellcheck",
    mason_id = true,
    require_node = false,
    auto_install = true,
  },
  {
    "shfmt",
    mason_id = true,
    require_node = false,
    auto_install = true,
  },
  -- {
  --   "stylua",
  --   mason_id = true,
  --   require_node = false,
  --   auto_install = true,
  -- },
}
