local palette = {
  Bg = "#16161e",
  BgShadeLight = "#1a1b26",
  BgShadeLighter = "#2a2f41",
  Fg = "#787c99",
  FgShadeDark = "#5b607f",
  FgShadeDarker = "#555b79",
  Black = "#13131b",
  Red = "#f7768e",
  Green = "#41a6b5",
  Yellow = "#e0af68",
  Orange = "#ff9e64",
  Blue = "#7aa2f7",
  Magenta = "#bb9af7",
  Cyan = "#7dcfff",
  White = "#c0caf5",
}

local M = {}
-- stylua: ignore
M.custom = {
  { "StatusLineNC",               { bg = palette.BgShadeLight, fg = "NONE" } },
  { "StatusLine",                 { bg = palette.BgShadeLight, fg = palette.FgShadeDarker } },
  { "StatusLineImp",              { bg = palette.BgShadeLight, fg = palette.Fg } },
  { "StatusLineInd",              { bg = palette.BgShadeLight, fg = palette.Green } },
  { "StatusLineDiagnosticError",  { bg = palette.BgShadeLight, fg = palette.Red } },
  { "StatusLineDiagnosticWarn",   { bg = palette.BgShadeLight, fg = palette.Magenta } },
  { "StatusLineDiagnosticHint",   { bg = palette.BgShadeLight, fg = palette.Cyan } },
  { "StatusLineDiagnosticInfo",   { bg = palette.BgShadeLight, fg = palette.Fg } },
  { "LineNr",                     { bg = "NONE", fg = palette.FgShadeDarker } },
  { "CursorLineNr",               { bg = palette.BgShadeLight, fg = palette.Fg, bold = false } },
  { "WinBar",                     { bg = palette.BgShadeLight, fg = palette.FgShadeDark } },
  { "WinBarNC",                   { bg = palette.BgShadeLight, fg = palette.FgShadeDark } },
  { "VertSplit",                  { fg = "#272834" } },
  { "PmenuSel",                   { bg = palette.BgShadeLighter , fg = palette.White } },
  { "PmenuSbar",                  { bg = palette.Bg  } },
  { "PmenuThumb",                 { bg = palette.BgShadeLighter } },
  { "TabLineFill",                { bg = "NONE" } },
  { "TabLine",                    { bg = "NONE", fg = palette.FgShadeDarker } },
  { "TabLineSel",                 { bg = "NONE", fg = palette.Orange } },
  { "TelescopeSelection",         { bg = palette.BgShadeLighter , fg = palette.White } },
  { "TelescopeNormal",            { bg = palette.BgShadeLight } },
  { "TelescopeBorder",            { bg = palette.BgShadeLight, fg = palette.BgShadeLight } },
  { "TelescopeResultsTitle",      { bg = palette.BgShadeLight, fg = palette.BgShadeLight } },
  { "FloatTitle",                 { bg = palette.Bg, fg = palette.White } },
  { "FloatBorder",                { bg = palette.Bg, fg = palette.BgShadeLighter } },
  { "NormalFloat",                { bg = palette.Bg, fg = palette.Fg } },
  { "NormalFloatAlt",             { bg = palette.BgShadeLight, fg = palette.Fg } },
  { "FloatBorderAlt",             { bg = palette.BgShadeLight, fg = palette.BgShadeLight } },
  { "LspReference",               { bg = palette.BgShadeLighter } },
  { "VimModeNormal",              { bg = "#041b4d", fg = palette.Blue } },
  { "VimModeInsert",              { bg = "#16373c", fg = palette.Green } },
  { "VimModeVisual",              { bg = "#521e00", fg = palette.Orange } },
  { "VimModeCommand",             { bg = "#1e064b", fg = palette.Magenta } },
  { "VimModeExtra",               { bg = "#4d0412", fg = palette.Red } },
  { "SnipChoiceNode",             { bg = palette.BgShadeLight, fg = palette.Orange } },
  { "SnipInsertNode",             { bg = palette.BgShadeLight, fg = palette.Green } },
  { "TroubleText",                { bg = "NONE", fg = palette.Fg } },
  { "TroubleFoldIcon",            { bg = "NONE", fg = palette.Fg } },
  { "Error",                      { bg = "NONE", fg = "NONE" } }, -- causes weird paren,brace highlighting on floating windows by default
  { "CmpItemAbbr",                { link = "NormalFloat" } },
}

return M.custom
